version: '2'

services:
    traefik:
        image: traefik:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/etc/traefik/traefik.toml:ro
            - ./.data/traefik/log/:/etc/traefik/log/
            - ./keys:/etc/traefik/keys:ro

    memcached:
        image: memcached:latest
        container_name: main_memcached
        restart: always

    db:
        image: mariadb:latest
        restart: always
        container_name: main_db
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    mailcatcher:
     image: schickling/mailcatcher
     labels:
       - "traefik.port=1080"
       - "traefik.frontend.rule=Host:mail.dev.localhost"
     environment:
       MAILCATCHER_PORT: 1025

    dbadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        labels:
            - "traefik.frontend.rule=Host:db.dev.localhost"
        environment:
            PMA_USER: root
            PMA_PASSWORD:

networks:
    default:
        external:
            name: dev
