version: '2'

services:
    traefik:
        image: traefik:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/etc/traefik/traefik.toml:ro
            - ./.data/traefik/log/:/etc/traefik/log/
            - ./keys:/etc/traefik/keys:ro

    memcached:
        image: memcached:latest
        container_name: main_memcached
        restart: always

    mcadmin:
        image: hitwe/phpmemcachedadmin
        restart: always
        depends_on:
            - memcached
        labels:
            - "traefik.frontend.rule=Host:mem.dev.localhost"
            - "traefik.frontend.redirect.entryPoint=https"

    db:
        image: mariadb:latest
        restart: always
        container_name: main_db
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        labels:
            - "traefik.port=3306"
            - "traefik.frontend.rule=Host:dbmain.dev.localhost"

    mailcatcher:
        environment:
            MAILCATCHER_PORT: 1025
        image: schickling/mailcatcher
        labels:
            - "traefik.port=1080"
            - "traefik.frontend.rule=Host:mail.dev.localhost"
            - "traefik.frontend.redirect.entryPoint=https"

    dbadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        labels:
            - "traefik.frontend.rule=Host:db.dev.localhost"
            - "traefik.frontend.redirect.entryPoint=https"

networks:
    default:
        external:
            name: dev
